---
sidebar: sidebar 
permalink: task-azure-key-vault.html 
keywords: azure, encryption, NVE, NetApp volume encryption, KMIP, azure key vault 
summary: Utilisez Azure Key Vault pour votre service tiers de gestion des clés. 
---
= Gérez les clés avec Azure Key Vault
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Vous pouvez utiliser link:https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts["Azure Key Vault (AKV)"^] Afin de protéger vos clés de chiffrement ONTAP dans une application déployée dans Azure.

AKV peut être utilisé pour protéger link:https://docs.netapp.com/us-en/ontap/configure-netapp-volume-encryption-concept.html["Clés NetApp Volume Encryption (NVE)"^] Uniquement pour les SVM de données.

La gestion des clés via AKV peut être activée via l'interface de ligne de commande ou l'API REST ONTAP.

Lorsque vous utilisez AKV, notez que par défaut une LIF de SVM de données permet de communiquer avec le terminal de gestion des clés cloud. Un réseau de gestion de nœuds est utilisé pour communiquer avec les services d'authentification du fournisseur de cloud (login.microsoftonline.com). Si le réseau de cluster n'est pas configuré correctement, le cluster n'utilisera pas correctement le service de gestion des clés.

.Prérequis
* Cloud Volumes ONTAP doit exécuter la version 9.10.1 ou ultérieure
* Licence Volume Encryption (VE) installée (la licence NetApp Volume Encryption est automatiquement installée sur chaque système Cloud Volumes ONTAP enregistré auprès du support NetApp).
* Licence MTEKM (Multi-tenant Encryption Key Management) installée
* Vous devez être un administrateur de cluster ou de SVM
* Un abonnement Active Azure


.Limites
* AKV ne peut être configuré que sur un SVM de données




== Processus de configuration

La procédure décrite ci-dessus décrit comment enregistrer votre configuration Cloud Volumes ONTAP avec Azure et comment créer un coffre-fort de clés Azure et des clés. Si vous avez déjà effectué ces étapes, vérifiez que vous disposez des paramètres de configuration corrects, notamment dans , puis passer à .

* 
* 
* 
* 
* 
* 


[[azure-app]]
.Inscription aux applications Azure
. Vous devez d'abord enregistrer votre application dans l'abonnement Azure que vous souhaitez que Cloud Volumes ONTAP utilise pour accéder au coffre-fort de clés Azure. Dans le portail Azure, sélectionnez **enregistrements d'applications**.
. Sélectionnez **Nouvelle inscription**.
. Indiquez un nom pour votre application et sélectionnez un type d'application pris en charge. Le locataire unique par défaut suffit pour l'utilisation d'Azure Key Vault. Sélectionnez **Enregistrer**.
. Dans la fenêtre Présentation d'Azure, sélectionnez l'application que vous avez enregistrée. Copiez l'ID de l'application (client) ** et l'ID du répertoire **(locataire)** dans un emplacement sécurisé. Elles seront requises plus tard dans le processus d'inscription.


[[secret]]
.Créez le secret du client Azure
. Dans le portail Azure de votre application Cloud Volumes ONTAP, sélectionnez le volet **Ceritificats & secrets**.
. Sélectionnez **Nouveau secret client** Entrez un nom significatif pour votre secret client. NetApp recommande une période d'expiration de 24 mois. Toutefois, vos règles de gouvernance cloud peuvent nécessiter un paramétrage différent.
. Sélectionnez **Ajouter** pour enregistrer le secret client. Copiez immédiatement la valeur **** du secret et stockez-la quelque part en toute sécurité pour une configuration future. La valeur secrète ne s'affiche pas lorsque vous vous éloignez de la page.


[[create-akv]]
.Créez un coffre-fort de clés Azure
. Si vous disposez déjà d'un coffre-fort de clés Azure, vous pouvez le connecter à votre configuration Cloud Volumes ONTAP, mais vous devez adapter les règles d'accès aux paramètres de ce processus.
. Dans le portail Azure, accédez à la section **Key Vaults**.
. Sélectionnez **Créer**. Entrez les informations requises, y compris le groupe de ressources, la région et le niveau de prix, et effectuez des sélections pour les jours de conservation des coffres-forts supprimés et si la protection de purge est activée ou non. Les valeurs par défaut sont suffisantes pour cette configuration. Toutefois, vos règles de gouvernance de cloud peuvent nécessiter des paramètres différents.
. Sélectionnez **Suivant** pour choisir une stratégie d'accès.
. Sélectionnez **chiffrement de disque Azure** pour l'option de chiffrement de volume et **politique d'accès au coffre-fort** pour le modèle d'autorisation.
. Sélectionnez **Ajouter une stratégie d'accès**.
. Sélectionnez le point adjacent au champ **configurer à partir du modèle (facultatif)**. Sélectionnez ensuite **Key, Secret, & Certification Management.**
. Choisissez chacun des menus déroulants d'autorisations (clé, secret, certificat), puis **Sélectionner tout ** en haut de la liste des menus pour sélectionner toutes les autorisations disponibles. Vous devez avoir :
+
** **Autorisations clés** : 19 sélectionnées
** **Autorisations secrètes**: 8 sélectionnées
** **Autorisations de certificat**: 16 sélectionné


. Sélectionnez **Ajouter** pour créer la stratégie d'accès.
. Sélectionnez **Suivant** pour passer aux options **mise en réseau**.
. Choisissez la méthode d'accès au réseau appropriée ou sélectionnez **tous les réseaux** et **Revue + Créer** pour créer le coffre-fort de clés. (La méthode d'accès au réseau peut être prescrite par une gouvernance ou par votre équipe de sécurité cloud.)
. Enregistrez l'URI du coffre-fort de clés : dans le coffre-fort de clés que vous avez créé, accédez au menu Aperçu et copiez l'URI du coffre-fort **** dans la colonne de droite. Vous en aurez besoin pour une étape ultérieure.


[[key]]
.Créez une clé de chiffrement
. Dans le menu du coffre-fort de clés créé pour Cloud Volumes ONTAP, accédez à l'option **touches**.
. Sélectionnez **générer/importer** pour créer une nouvelle clé.
. Laissez l'option par défaut sur **générer**.
. Fournissez les informations suivantes :
+
** Nom de la clé de chiffrement
** Type de clé : RSA
** Taille de la clé RSA : 2048
** Activé : Oui


. Sélectionnez **Créer** pour créer la clé de cryptage.
. Revenez au menu **touches** et sélectionnez la touche que vous venez de créer.
. Sélectionnez l'ID de clé sous **version actuelle** pour afficher les propriétés de la clé.
. Repérez le champ **Key identifier**. Copiez l'URI vers mais sans inclure la chaîne hexadécimale.


[[AAD]]
.Création d'un terminal Azure Active Directory (HA uniquement)
. Ce processus n'est requis que si vous configurez Azure Key Vault pour un environnement de travail Cloud Volumes ONTAP haute disponibilité.
. Dans le portail Azure, accédez à **réseaux virtuels**.
. Sélectionnez le réseau virtuel sur lequel vous avez déployé l'environnement de travail Cloud Volumes ONTAP et sélectionnez le menu **sous-réseaux** sur le côté gauche de la page.
. Sélectionnez dans la liste le nom de sous-réseau de votre déploiement Cloud Volumes ONTAP.
. Naviguez jusqu'à l'en-tête **points d'extrémité du service**. Dans le menu déroulant, sélectionnez **Microsoft.AzureActiveDirectory** dans la liste.
. Sélectionnez **Enregistrer** pour capturer vos paramètres.


[[ontap]]
.Configuration Cloud Volumes ONTAP
. Connectez-vous à la LIF de gestion du cluster avec votre client SSH préféré.
. Entrez le mode de privilège avancé dans ONTAP :
`set advanced -con off``
. Identifier le SVM de données souhaité et vérifier sa configuration DNS :
`vserver services name-service dns show`
+
.. Si une entrée DNS pour le SVM de données souhaité existe et qu'elle contient une entrée pour le DNS Azure, aucune action n'est requise. Si ce n'est pas le cas, ajoutez une entrée de serveur DNS pour le SVM de données qui pointe vers le DNS Azure, le DNS privé ou le serveur sur site. Ceci doit correspondre à l'entrée pour le SVM admin du cluster :
`vserver services name-service dns create -vserver _SVM_name_ -domains _domain_ -name-servers _IP_address_`
.. Vérifier que le service DNS a été créé pour le SVM de données :
`vserver services name-service dns show`


. Activez le coffre-fort de clés Azure à l'aide de l'ID client et de l'ID locataire enregistrés après l'enregistrement de l'application :
`security key-manager external azure enable -vserver _SVM_name_ -client-id _Azure_client_ID_ -tenant-id _Azure_tenant_ID_ -name _Azure_key_name_ -key-id _Azure_key_ID_`
. Vérifiez la configuration du gestionnaire de clés :
`security key-manager external azure show`
. Vérifier le statut du gestionnaire de clés :
`security key-manager external azure check`Le résultat sera le suivant :
+
[source]
----
::*> security key-manager external azure check

Vserver: data_svm_name
Node: akvlab01-01

Category: service_reachability
    Status: OK

Category: ekmip_server
    Status: OK

Category: kms_wrapped_key_status
    Status: UNKNOWN
    Details: No volumes created yet for the vserver. Wrapped KEK status will be available after creating encrypted volumes.

3 entries were displayed.
----
+
Si le `service_reachability` l'état n'est pas `OK`, La SVM ne peut pas atteindre le service Azure Key Vault avec toutes les connectivités et autorisations requises. Le `kms_wrapped_key_status` rapports `UNKNOWN` lors de la configuration initiale. Son statut devient `OK` une fois le premier volume crypté.

. FACULTATIF : créez un volume de test pour vérifier le fonctionnement de NVE.
+
`vol create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggr_ -size _size_ -state online -policy default`

+
S'il est correctement configuré, Cloud Volumes ONTAP crée automatiquement le volume et active le chiffrement de volume.

. Confirmez que le volume a été créé et chiffré correctement. Si c'est le cas, le `-is-encrypted` le paramètre s'affiche comme `true`.
`vol show -vserver _SVM_name_ -fields is-encrypted`

