---
sidebar: sidebar 
permalink: task-manage-aggregates.html 
keywords: aggregates, delete aggregates, add disks, view aggregates 
summary: Gérez vous-même les agrégats en ajoutant des disques, en affichant les informations sur les agrégats et en les supprimant. 
---
= Gestion des agrégats
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gérez vous-même les agrégats en ajoutant des disques, en affichant les informations sur les agrégats et en les supprimant.


CAUTION: Tous les disques et agrégats doivent être créés et supprimés directement depuis BlueXP. Vous ne devez pas effectuer ces actions à partir d'un autre outil de gestion. Cela peut avoir un impact sur la stabilité du système, entraver la possibilité d'ajouter des disques à l'avenir et générer potentiellement des frais de fournisseur de cloud redondant.

Si vous souhaitez supprimer un agrégat, vous devez d'abord supprimer les volumes de l'agrégat.

Si un agrégat manque d'espace de stockage, il est possible de déplacer des volumes vers un autre agrégat via System Manager.

.Étapes
. Dans le menu de navigation de gauche, sélectionnez *stockage > Canvas*.
. Sur la page Canevas, double-cliquez sur l'environnement de travail Cloud Volumes ONTAP dans lequel vous souhaitez gérer les agrégats.
. Cliquez sur l'icône du menu, puis sur *Avancé > attribution avancée*.
. Gérez vos agrégats :
+
[cols="30,70"]
|===
| Tâche | Action 


| Afficher des informations sur un agrégat | Sélectionnez un agrégat et cliquez sur *Info*. 


| Créez un volume sur un agrégat spécifique | Sélectionnez un agrégat et cliquez sur *Create volume*. 


| Ajoutez des disques à un agrégat  a| 
.. Sélectionnez un agrégat et cliquez sur *Add disks*.
.. Sélectionnez le nombre de disques que vous souhaitez ajouter et cliquez sur *Ajouter*.
+

TIP: Tous les disques qui composent un agrégat doivent être de la même taille.



ifdef::aws[]



| Augmentation de la capacité d'un agrégat prenant en charge Amazon EBS Elastic volumes  a| 
.. Sélectionnez un agrégat et cliquez sur *augmenter la capacité*.
.. Saisissez la capacité supplémentaire que vous souhaitez ajouter, puis cliquez sur *Ajouter*.
+
Notez que vous devez augmenter la capacité de l'agrégat d'au moins 256 Gio ou 10 % de la taille de l'agrégat.

+
Par exemple, si vous avez un agrégat de 1.77 Tio, 10 % est égal au 181 Gio. Soit plus faible que 256 Gio, donc la taille de l'agrégat doit être augmentée de 256 Gio au minimum.



endif::aws[]



| Supprimer un agrégat  a| 
.. Sélectionnez un agrégat qui ne contient aucun volume et cliquez sur *Supprimer*.
.. Cliquez à nouveau sur *Supprimer* pour confirmer.


|===

