---
sidebar: sidebar 
permalink: task-modify-write-speed.html 
keywords: write speed, high write speed, normal write speed, change write speed 
summary: 'Il peut être nécessaire de modifier la configuration des systèmes Cloud Volumes ONTAP au fur et à mesure de l"évolution de vos besoins de stockage. Vous pouvez, par exemple, choisir entre les configurations de paiement à l"utilisation, modifier le type d"instance ou d"ordinateur virtuel, et bien plus encore.' 
---
= Modifier la vitesse d'écriture du système
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP vous permet de choisir une vitesse d'écriture normale ou élevée pour Cloud Volumes ONTAP. La vitesse d'écriture par défaut est normale. Vous pouvez passer à une vitesse d'écriture élevée si vos workloads nécessitent des performances d'écriture rapides.

Une vitesse d'écriture élevée est prise en charge avec tous les types de systèmes à un nœud et certaines configurations de paires HA. Affichez les configurations prises en charge dans le https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Notes de version de Cloud Volumes ONTAP"^]

Avant de modifier la vitesse d'écriture, vous devez link:concept-write-speed.html["comprendre les différences entre les réglages normaux et élevés"].

.Description de la tâche
* Assurez-vous que les opérations telles que la création de volume ou d'agrégat ne sont pas en cours.
* Notez que cette modification redémarre le système Cloud Volumes ONTAP. Il s'agit d'un processus perturbateur qui requiert des temps d'indisponibilité pour l'ensemble du système.


.Étapes
. Dans l'environnement de travail, cliquez sur l'icône de menu, puis sur *Avancé > vitesse d'écriture*.
. Sélectionnez *Normal* ou *Haut*.
+
Si vous choisissez Haut, vous devrez lire l'énoncé « Je comprends... » et confirmer en cochant la case.

. Cliquez sur *Enregistrer*, vérifiez le message de confirmation, puis cliquez sur *Continuer*.

