---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP prend en charge NVE (NetApp Volume Encryption) et NAE (NetApp Aggregate Encryption) avec un gestionnaire de clés externe. NVE et NAE sont activés par défaut si vous configurez un gestionnaire de clés externe.' 
---
= Cryptage de volumes grâce aux solutions de cryptage NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Volumes ONTAP prend en charge NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE). NVE et NAE sont des solutions logicielles qui permettent le chiffrement des données au repos conforme à la norme FIPS 140-2. link:concept-security.html["En savoir plus sur ces solutions de cryptage"].

NVE et NAE sont pris en charge par un gestionnaire de clés externe.

ifdef::azure[]

endif::azure[]

ifdef::gcp[]

endif::gcp[]

NAE est activé sur les nouveaux agrégats par défaut après avoir configuré un gestionnaire de clés externe. NVE est activé par défaut sur les nouveaux volumes qui ne font pas partie d'un agrégat NAE (par exemple, si des agrégats existants ont été créés avant de configurer un gestionnaire de clés externe).

Cloud Volumes ONTAP ne prend pas en charge la gestion intégrée des clés.

.Ce dont vous avez besoin
Votre système Cloud Volumes ONTAP doit être enregistré auprès du support NetApp. Une licence NetApp Volume Encryption est automatiquement installée sur chaque système Cloud Volumes ONTAP enregistré auprès du support NetApp.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html["Ajout de comptes du site de support NetApp à BlueXP"^]
* link:task-registering.html["Enregistrement des systèmes de paiement à l'utilisation"]



NOTE: BlueXP n'installe pas la licence NVE sur les systèmes qui résident dans la région Chine.

.Étapes
. Consultez la liste des gestionnaires de clés pris en charge dans le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].
+

TIP: Recherchez la solution *gestionnaires de clés*.

. link:task-connecting-to-otc.html["Connectez-vous à l'interface de ligne de commandes de Cloud Volumes ONTAP"^].
. Configurez la gestion externe des clés.
+
ifdef::aws[]

+
** AWS : https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-overview-concept.html["Pour obtenir des instructions, consultez la documentation ONTAP"^]




endif::aws[]

ifdef::azure[]

* Azure : link:task-azure-key-vault.html["Azure Key Vault (AKV)"]


endif::azure[]

ifdef::gcp[]

* Google Cloud : link:task-google-key-manager.html["Service Google Cloud Key Management"]


endif::gcp[]
